"""
data_contract.py
────────────────
Transforms the raw Gemini JSON into the canonical Cometa data contract:

    {
      "submission": { ...metadata + dedup key... },
      "kpi_rows":   [ ...one row per KPI...       ],
      "raw_gemini": { ...original Gemini output... }
    }

Rules enforced here:
  Rule 4  – Every metric value is parsed and validated as numeric.
             Non-numeric values are stored with is_valid=False.
  Rule 8  – file_hash is embedded in `submission` as the deduplication key.
  Bonus   – period_id is inferred from the document and checked for
             consistency across all rows.
"""

import json
import re
import uuid
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.core.fx_service import get_fx_provider


# ── KPI Registry ──────────────────────────────────────────────────────────────
# Loaded dynamically from assets/loading_brain_v1.json so it always mirrors the
# 109-KPI master catalog.  Paths are flat: ["financial_metrics_2025", metric_id]
# which matches the Gemini extraction prompt generated by _build_gemini_kpi_schema().
#
# Falls back to a minimal hardcoded set if the brain file is unavailable.

_BRAIN_PATH = Path(__file__).parent.parent.parent / "assets" / "loading_brain_v1.json"

_DATA_TYPE_TO_UNIT: dict[str, str] = {
    "currency":   "usd",
    "percentage": "pct",
    "integer":    "count",
    "float":      "count",
    "ratio":      "pct",
}


def _build_kpi_registry() -> list[dict]:
    """
    Auto-generates KPI_REGISTRY from loading_brain_v1.json.

    Only GIVEN KPIs are included (SILVER KPIs are calculated in BigQuery and do
    not need to be extracted from the document).  Paths are flat:
        ["financial_metrics_2025", metric_id]
    """
    try:
        with open(_BRAIN_PATH, encoding="utf-8") as f:
            brain = json.load(f)
        registry: list[dict] = []
        for m in brain.get("metrics", []):
            if m.get("given_or_silver") != "GIVEN":
                continue
            metric_id  = m.get("metric_id", "")
            if not metric_id:
                continue
            unit_type = _DATA_TYPE_TO_UNIT.get(m.get("data_type", ""), "usd")
            entry: dict = {
                "kpi_key":   metric_id,
                "kpi_label": m.get("display_name", metric_id),
                "path":      ["financial_metrics_2025", metric_id],
                "unit_type": unit_type,
            }
            if m.get("aliases"):
                entry["aliases"] = m["aliases"]
            registry.append(entry)
        if registry:
            return registry
    except Exception as exc:
        import sys
        print(f"[data_contract] WARN: could not load brain registry: {exc}", file=sys.stderr)

    # ── Minimal fallback — covers the core innegociables ──────────────────
    return [
        {"kpi_key": "revenue",        "kpi_label": "Revenue",           "path": ["financial_metrics_2025", "revenue"],        "unit_type": "usd"},
        {"kpi_key": "gross_profit",   "kpi_label": "Gross Profit",      "path": ["financial_metrics_2025", "gross_profit"],   "unit_type": "usd"},
        {"kpi_key": "ebitda",         "kpi_label": "EBITDA",            "path": ["financial_metrics_2025", "ebitda"],         "unit_type": "usd"},
        {"kpi_key": "cash",           "kpi_label": "Cash",              "path": ["financial_metrics_2025", "cash"],           "unit_type": "usd"},
        {"kpi_key": "burn",           "kpi_label": "Burn",              "path": ["financial_metrics_2025", "burn"],           "unit_type": "usd"},
        {"kpi_key": "mrr",            "kpi_label": "MRR",               "path": ["financial_metrics_2025", "mrr"],            "unit_type": "usd"},
        {"kpi_key": "employees",      "kpi_label": "Employees",         "path": ["financial_metrics_2025", "employees"],      "unit_type": "count"},
    ]


KPI_REGISTRY: list[dict] = _build_kpi_registry()


# ── Sector requirements checklist ──────────────────────────────────────────────
# KPIs that MUST be present for a submission to be considered complete per sector.

SECTOR_REQUIREMENTS: dict[str, list[str]] = {
    "SAAS":  ["revenue", "mrr", "churn_rate", "cac"],
    "LEND":  ["revenue", "portfolio_size", "npl_ratio"],
    "ECOM":  ["revenue", "gmv", "cac"],
    "INSUR": ["revenue", "loss_ratio", "cac"],
    "OTH":   ["revenue", "ebitda"],
}


# ── Unit synonym normalization ────────────────────────────────────────────────
# Gemini sometimes returns the unit field (or a fallback unit_type) using
# text synonyms instead of canonical symbols.  Mapping them here eliminates
# spurious WARN [unit_mismatch] entries downstream without changing semantics.

_UNIT_SYNONYMS: dict[str, str] = {
    # USD / money synonyms  →  canonical "$"
    "usd":        "$",
    "dollars":    "$",
    "usd_amount": "$",
    "us dollars": "$",
    "mxn":        "$",   # treated as dollar-class for unit check; FX handled separately
    "eur":        "$",
    "brl":        "$",
    "cop":        "$",
    # Percentage synonyms  →  canonical "%"
    "pct":        "%",
    "percentage": "%",
    "ratio":      "%",
    "decimal":    "%",
    "rate":       "%",
}


def _normalize_unit_synonym(unit: str) -> str:
    """
    Map a raw unit string to its canonical symbol ("$" or "%").

    Scale suffixes (M, K, B) are preserved: "usdM" → "$M", "pct" → "%".
    The lookup is case-insensitive and strips leading/trailing whitespace.

    Returns the original string unchanged if no synonym matches, so callers
    can safely pass any unit without risk of silent corruption.
    """
    if not unit:
        return unit
    stripped = unit.strip()
    # Separate scale suffix (M / K / B) if present
    lower = stripped.lower()
    # Check full string first
    if lower in _UNIT_SYNONYMS:
        return _UNIT_SYNONYMS[lower]
    # Check base without trailing scale letter
    if len(lower) > 1 and lower[-1] in ("m", "k", "b"):
        base  = lower[:-1]
        scale = stripped[-1].upper()
        if base in _UNIT_SYNONYMS:
            return _UNIT_SYNONYMS[base] + scale
    return stripped


# ── Internal helpers ──────────────────────────────────────────────────────────

def _dig(obj: dict, path: list[str]) -> Optional[dict]:
    """
    Navigate a nested dict by a list of keys.
    Returns the node at the end of the path, or None if any key is missing.
    """
    current = obj
    for key in path:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


# Sufijos de texto que Gemini añade y que no son multiplicadores numéricos.
# Se eliminan ANTES de parsear para evitar is_valid=False por ruido léxico.
_NOISE_WORDS = re.compile(
    r"\b("
    r"units?|employees?|people|persons?|headcount|"
    r"months?|years?|days?|weeks?|quarters?|"
    r"customers?|clients?|users?|accounts?|"
    r"transactions?|contracts?|"
    r"approx(?:imately)?|estimated?|projected?|"
    r"usd|mxn|cop|brl|ars|eur|gbp|clp|pen"   # monedas como texto (ya se maneja por símbolo)
    r")\b",
    re.IGNORECASE,
)

def _sanitize_noise(raw: Optional[str]) -> Optional[str]:
    """
    Elimina ruido léxico que Gemini añade a los valores numéricos.

    Ejemplos:
      '107,466 units'   → '107,466'
      '0 units'         → '0'
      '12 employees'    → '12'
      '18 months'       → '18'
      '$4.2M USD'       → '$4.2M'   (USD como texto se elimina; $ ya lo maneja parse_numeric)
      '84%'             → '84%'     (sin cambio — % no es noise)
    """
    if raw is None or not isinstance(raw, str):
        return raw
    cleaned = _NOISE_WORDS.sub("", raw).strip()
    # Colapsar espacios internos generados por la eliminación
    cleaned = re.sub(r"\s{2,}", " ", cleaned).strip()
    return cleaned if cleaned else raw


def parse_numeric(raw: Optional[str]) -> tuple[Optional[float], Optional[str]]:
    """
    Rule 4 — Convert a financial string to (numeric_value, unit_detected).

    Handles:
      "36%"            → (36.0,          "%")
      "$9.7M"          → (9_700_000.0,   "$M")
      "-0.74%"         → (-0.74,         "%")
      "$1.1K"          → (1_100.0,       "$K")
      "$4.2B"          → (4_200_000_000, "$B")
      "107,466 units"  → (107_466.0,     None)   ← sanitized
      "0 units"        → (0.0,           None)   ← sanitized
      "null"           → (None,           None)

    Returns (None, None) for any value that cannot be made numeric.
    """
    if raw is None or str(raw).strip().lower() in ("null", "n/a", "---", "", "none"):
        return None, None

    # Pre-sanitize: eliminar ruido léxico antes de parsear
    raw = _sanitize_noise(raw)

    s = str(raw).strip()
    is_negative = s.startswith("-")
    s = s.lstrip("+-")

    # Detect base unit symbol
    unit: Optional[str] = None
    if "%" in s:
        unit = "%"
        s = s.replace("%", "")
    elif "$" in s:
        unit = "$"
        s = s.replace("$", "")

    # Detect scale multiplier
    multiplier = 1.0
    upper_s = s.upper()
    if upper_s.endswith("B"):
        multiplier = 1_000_000_000.0
        s = s[:-1]
        unit = (unit or "") + "B"
    elif upper_s.endswith("M"):
        multiplier = 1_000_000.0
        s = s[:-1]
        unit = (unit or "") + "M"
    elif upper_s.endswith("K"):
        multiplier = 1_000.0
        s = s[:-1]
        unit = (unit or "") + "K"

    s = s.replace(",", "").strip()

    try:
        value = float(s) * multiplier
        return (-value if is_negative else value), unit
    except ValueError:
        return None, None


def detect_currency(gemini_json: dict) -> str:
    """
    Extract the document currency from the _document_context block written
    by Gemini's FASE 1 analysis.

    Falls back to 'USD' if the field is absent, malformed, or not a 3-letter
    ISO 4217 code — conservative default to avoid silent conversion errors.
    """
    ctx = gemini_json.get("_document_context") or {}
    raw = ctx.get("currency", "USD")
    if not isinstance(raw, str):
        return "USD"
    code = raw.strip().upper()
    # Accept only plausible ISO 4217 codes (3 uppercase letters)
    return code if re.fullmatch(r"[A-Z]{3}", code) else "USD"


def _period_year(period_id: str) -> int:
    """
    Extract the 4-digit reporting year from a period_id string.
    Examples: 'FY2025' → 2025,  'H1 2025' → 2025,  '2025' → 2025.
    Falls back to current year if no 20XX pattern is found.
    """
    match = re.search(r"(20\d{2})", period_id)
    return int(match.group(1)) if match else datetime.now(timezone.utc).year


_INFER_CANONICAL_RE = re.compile(r"P(20\d{2})Q([1-4])M(\d{2})")
_INFER_MONTH_MAP = {
    "january": "01", "february": "02", "march": "03", "april": "04",
    "may": "05", "june": "06", "july": "07", "august": "08",
    "september": "09", "october": "10", "november": "11", "december": "12",
    "enero": "01", "febrero": "02", "marzo": "03", "abril": "04",
    "mayo": "05", "junio": "06", "julio": "07", "agosto": "08",
    "septiembre": "09", "octubre": "10", "noviembre": "11", "diciembre": "12",
}
_INFER_MONTH_QUARTER = {
    "01": "Q1", "02": "Q1", "03": "Q1",
    "04": "Q2", "05": "Q2", "06": "Q2",
    "07": "Q3", "08": "Q3", "09": "Q3",
    "10": "Q4", "11": "Q4", "12": "Q4",
}


def infer_period_id(gemini_json: dict) -> str:
    """
    Infer the reporting period from description fields inside the Gemini JSON.

    Priority chain (stops at first match):
      0. _document_context.period is already canonical PYYYYQxMyy  → passthrough
      1. _document_context.period contains month name + year → map to canonical
      2. Any PYYYYQxMyy pattern anywhere in the JSON text
      3. Most-frequent 20XX year → FY<year>
      4. Current year fallback
    """
    ctx = gemini_json.get("_document_context") or {}

    # ── 0: canonical period from Gemini context ────────────────────────────
    raw_ctx_period = str(ctx.get("period", "") or "").strip()
    if _INFER_CANONICAL_RE.fullmatch(raw_ctx_period):
        return raw_ctx_period

    # ── 1: month name + year anywhere in context.period ───────────────────
    if raw_ctx_period:
        p_lower = raw_ctx_period.lower()
        year_m = re.search(r"(20\d{2})", raw_ctx_period)
        if year_m:
            year = year_m.group(1)
            for month_name, month_num in _INFER_MONTH_MAP.items():
                if month_name in p_lower:
                    q = _INFER_MONTH_QUARTER[month_num]
                    return f"P{year}{q}M{month_num}"

    # ── 2: canonical pattern anywhere in JSON text ─────────────────────────
    json_text = str(gemini_json)
    canon_matches = _INFER_CANONICAL_RE.findall(json_text)
    if canon_matches:
        # Take the most common (year, quarter, month) triplet
        from collections import Counter as _Counter
        best = _Counter(canon_matches).most_common(1)[0][0]
        year, quarter, month = best
        return f"P{year}Q{quarter}M{month}"

    # ── 3: most-frequent year → FY fallback ───────────────────────────────
    year_pat = re.compile(r'\b(20\d{2})\b')
    matches = year_pat.findall(json_text)
    if matches:
        from collections import Counter as _Counter2
        return "FY" + _Counter2(matches).most_common(1)[0][0]

    # ── 4: current year ────────────────────────────────────────────────────
    return f"FY{datetime.now(timezone.utc).year}"


# ── Derivation engine ─────────────────────────────────────────────────────────

def calculate_derived_kpis(
    kpi_rows: list[dict],
    submission_id: str,
    period_id: str,
    currency: str,
) -> list[dict]:
    """
    Compute KPIs that can be derived mathematically from base metrics.

    Rules
    -----
    1. gross_margin  = (revenue - cogs) / revenue  — if revenue > 0 and cogs present.
       Only added if gross_profit_margin was NOT already extracted by Gemini.
    2. ebitda_margin = ebitda / revenue             — if revenue > 0 and ebitda present.
       Only added if ebitda_margin was NOT already extracted by Gemini.

    Returns a (possibly empty) list of new kpi_row dicts to append to kpi_rows.
    All derived rows carry confidence=1.0 and source_description='calculated'.
    """
    # Build index of existing valid rows for quick lookup
    valid_index: dict[str, float] = {
        r["kpi_key"]: r["numeric_value"]
        for r in kpi_rows
        if r.get("is_valid") and r.get("numeric_value") is not None
    }
    existing_keys = {r["kpi_key"] for r in kpi_rows}

    derived: list[dict] = []

    def _derived_row(kpi_key: str, kpi_label: str, value: float, unit: str) -> dict:
        return {
            "submission_id":      submission_id,
            "kpi_key":            kpi_key,
            "kpi_label":          kpi_label,
            "raw_value":          f"{round(value * 100, 4)}%" if unit == "%" else str(round(value, 6)),
            "numeric_value":      round(value, 6),
            "unit":               unit,
            "period_id":          period_id,
            "source_description": "calculated",
            "is_valid":           True,
            "original_currency":  currency,
            "fx_rate":            1.0 if currency == "USD" else None,
            "normalized_value_usd": round(value, 6) if currency == "USD" else None,
            "confidence":         1.0,
        }

    revenue = valid_index.get("revenue")

    # Rule 1: gross_margin from revenue + cogs
    if (
        revenue and revenue != 0
        and "cogs" in valid_index
        and "gross_profit_margin" not in existing_keys
    ):
        cogs = valid_index["cogs"]
        gross_margin = (revenue - cogs) / revenue
        derived.append(_derived_row("gross_profit_margin", "Gross Profit Margin (calc)", gross_margin, "%"))
        print(f"[Calc] gross_profit_margin derived: {gross_margin:.4f}")

    # Rule 2: ebitda_margin from ebitda + revenue
    if (
        revenue and revenue != 0
        and "ebitda" in valid_index
        and "ebitda_margin" not in existing_keys
    ):
        ebitda = valid_index["ebitda"]
        ebitda_margin = ebitda / revenue
        derived.append(_derived_row("ebitda_margin", "EBITDA Margin (calc)", ebitda_margin, "%"))
        print(f"[Calc] ebitda_margin derived: {ebitda_margin:.4f}")

    return derived


# ── Sector checklist ───────────────────────────────────────────────────────────

def build_checklist_status(kpi_rows: list[dict], bucket_id: str) -> dict:
    """
    Validate whether the submission contains all mandatory KPIs for its sector.

    Parameters
    ----------
    kpi_rows  : list of kpi_row dicts from build_contract (including derived).
    bucket_id : company vertical — SAAS | LEND | ECOM | INSUR | OTH | UNKNOWN.

    Returns
    -------
    {
      "bucket":               str,
      "is_complete":          bool,
      "present_kpis":         [str],
      "missing_critical_kpis":[str],
      "display_message":      str,
    }
    """
    required = SECTOR_REQUIREMENTS.get(bucket_id, [])

    present_valid = {
        r["kpi_key"]
        for r in kpi_rows
        if r.get("is_valid") and r.get("numeric_value") is not None
    }

    missing = [kpi for kpi in required if kpi not in present_valid]
    is_complete = len(missing) == 0

    if not required:
        message = f"Sector '{bucket_id}' sin checklist definido — revisa SECTOR_REQUIREMENTS."
    elif is_complete:
        message = f"Reporte {bucket_id} completo. Todos los KPIs criticos presentes."
    else:
        missing_str = ", ".join(missing)
        sector_labels = {
            "SAAS": "SaaS", "LEND": "Lending", "ECOM": "E-Commerce",
            "INSUR": "Insurance", "OTH": "General",
        }
        label = sector_labels.get(bucket_id, bucket_id)
        message = f"Atencion: Reporte {label} incompleto. Faltan: {missing_str}."

    return {
        "bucket":                bucket_id,
        "is_complete":           is_complete,
        "present_kpis":          sorted(present_valid),
        "missing_critical_kpis": missing,
        "display_message":       message,
    }


# ── Public API ────────────────────────────────────────────────────────────────

def build_contract(
    gemini_json: dict,
    file_hash: str,
    company_id: str,
    founder_email: str,
    original_filename: str,
    portfolio_id: str = "",
) -> dict:
    """
    Build the canonical data contract from a parsed Gemini response.

    Parameters
    ----------
    gemini_json       : The dict returned by Gemini (already json.loads'd).
    file_hash         : SHA-256 prefix of the PDF — deduplication key (Rule 8).
    company_id        : Domain of the submitting company.
    founder_email     : Email address of the uploader.
    original_filename : Original PDF filename.

    Returns
    -------
    {
      "submission": {
          submission_id, file_hash, company_id, founder_email,
          original_filename, submitted_at, period_id,
          period_consistent, kpi_count_total, kpi_count_valid, status
      },
      "kpi_rows": [
          { submission_id, kpi_key, kpi_label, raw_value,
            numeric_value, unit, period_id, source_description, is_valid },
          ...
      ],
      "raw_gemini": { ...original dict... },
      "integrity": {
          "period_consistent": bool,
          "valid_ratio": float,
          "warnings": [str]
      }
    }
    """
    submission_id = str(uuid.uuid4())
    period_id     = infer_period_id(gemini_json)
    now           = datetime.now(timezone.utc).isoformat()

    # ── Currency & FX setup ────────────────────────────────────────────────
    currency    = detect_currency(gemini_json)
    report_year = _period_year(period_id)
    fx          = get_fx_provider()

    if currency != "USD":
        print(
            f"💱 [Contract] Non-USD document detected — "
            f"currency={currency}, year={report_year}. "
            f"normalized_value_usd will be computed for each KPI."
        )

    # ── Build kpi_rows ─────────────────────────────────────────────────────
    kpi_rows: list[dict] = []
    warnings: list[str]  = []

    for kpi_def in KPI_REGISTRY:
        node = _dig(gemini_json, kpi_def["path"])

        raw_value   = None
        description = None

        if isinstance(node, dict):
            raw_value   = node.get("value")
            description = node.get("description")
        elif node is not None:
            # Gemini returned a scalar instead of {value, description}
            raw_value = str(node)
            warnings.append(
                f"KPI '{kpi_def['kpi_key']}' node is not a dict: {type(node).__name__}"
            )

        # Rule 4: validate numeric
        numeric_value, unit = parse_numeric(raw_value)
        is_valid = numeric_value is not None

        if raw_value is not None and not is_valid:
            warnings.append(
                f"KPI '{kpi_def['kpi_key']}' value '{raw_value}' is not numeric — "
                "stored with is_valid=False"
            )

        # Confidence — read from the Gemini node; default 0.0 if absent
        confidence: Optional[float] = None
        if isinstance(node, dict):
            raw_conf = node.get("confidence")
            try:
                confidence = float(raw_conf) if raw_conf is not None else None
            except (TypeError, ValueError):
                confidence = None

        # ── FX normalization ───────────────────────────────────────────────
        # Three columns written to fact_kpi_values:
        #   numeric_value       — parsed float in the document's original currency
        #   original_currency   — ISO 4217 code (e.g. "MXN")
        #   fx_rate             — annual-average units-of-currency per 1 USD
        #   normalized_value_usd — numeric_value / fx_rate  (USD equivalent)
        #
        # For USD documents fx_rate is always 1.0 and normalized == numeric.
        # For non-USD, fx_rate comes from StaticFxProvider (or future live API).
        if numeric_value is not None:
            if currency == "USD":
                fx_rate_used:          Optional[float] = 1.0
                normalized_value_usd:  Optional[float] = numeric_value
            else:
                fx_rate_used = fx.get_rate(currency, report_year)
                if fx_rate_used is not None:
                    normalized_value_usd = round(numeric_value / fx_rate_used, 6)
                else:
                    normalized_value_usd = None
                    warnings.append(
                        f"KPI '{kpi_def['kpi_key']}': no FX rate for "
                        f"{currency}/{report_year} — normalized_value_usd is null. "
                        "Add the currency to RATE_TABLE in fx_service.py."
                    )
        else:
            fx_rate_used         = None
            normalized_value_usd = None

        # Normalize unit: map Gemini synonyms (usd, pct, …) to canonical symbols
        # ($, %) so audit_contract never fires a spurious unit_mismatch warning.
        raw_unit = unit or kpi_def["unit_type"]
        normalized_unit = _normalize_unit_synonym(raw_unit)

        kpi_rows.append({
            "submission_id":      submission_id,
            "kpi_key":            kpi_def["kpi_key"],
            "kpi_label":          kpi_def["kpi_label"],
            "raw_value":          str(raw_value) if raw_value is not None else None,
            "numeric_value":      numeric_value,
            "unit":               normalized_unit,
            "period_id":          period_id,
            "source_description": description,
            "is_valid":           is_valid,
            # Mejora A — FX normalization: original value + rate + USD equivalent
            "original_currency":    currency,
            "fx_rate":              fx_rate_used,
            "normalized_value_usd": normalized_value_usd,
            # Mejora C — Confidence from Gemini FASE 2
            "confidence":           confidence,
        })

    # ── Derivation engine ──────────────────────────────────────────────────
    derived_rows = calculate_derived_kpis(kpi_rows, submission_id, period_id, currency)
    kpi_rows.extend(derived_rows)

    # ── Integrity checks ───────────────────────────────────────────────────
    valid_count = sum(1 for r in kpi_rows if r["is_valid"])
    valid_ratio = round(valid_count / len(kpi_rows), 2) if kpi_rows else 0.0

    # Period consistency: all rows carry the same period_id (single-pass
    # logic guarantees this today; flag is a future-proof hook).
    distinct_periods = {r["period_id"] for r in kpi_rows}
    period_consistent = len(distinct_periods) <= 1

    if not period_consistent:
        warnings.append(
            f"Multiple period_ids detected: {distinct_periods}. "
            "Check that the document covers a single fiscal year."
        )

    if valid_count == 0:
        warnings.append(
            "No numeric KPI values were extracted. "
            "The document may not contain financial statements in a parseable format."
        )

    # ── Mejora C: Confidence threshold ────────────────────────────────────
    # MVP demo threshold: 0.80 (era 0.85 — bajado para Hunty demo 2026-04-08).
    # Restaurar a 0.85 post-demo o cuando los prompts de Gemini sean más precisos.
    CONFIDENCE_THRESHOLD = 0.80
    conf_scores = [r["confidence"] for r in kpi_rows if r["confidence"] is not None]
    avg_confidence: Optional[float] = round(sum(conf_scores) / len(conf_scores), 3) if conf_scores else None

    if avg_confidence is not None and avg_confidence < CONFIDENCE_THRESHOLD:
        status = "pending_human_review"
        warnings.append(
            f"Average confidence {avg_confidence:.2f} is below threshold "
            f"{CONFIDENCE_THRESHOLD}. Submission flagged for human review."
        )
    elif valid_count > 0:
        status = "processed"
    else:
        status = "empty"

    # ── Build submission ───────────────────────────────────────────────────
    submission = {
        "submission_id":     submission_id,
        "file_hash":         file_hash,        # Rule 8: deduplication key
        "company_id":        company_id,
        "founder_email":     founder_email,
        "original_filename": original_filename,
        "submitted_at":      now,
        "period_id":         period_id,
        "period_consistent": period_consistent,
        "kpi_count_total":   len(kpi_rows),
        "kpi_count_valid":   valid_count,
        "avg_confidence":    avg_confidence,
        "status":            status,
        "detected_currency": currency,
        "portfolio_id":      portfolio_id,
    }

    return {
        "submission": submission,
        "kpi_rows":   kpi_rows,
        "raw_gemini": gemini_json,
        "integrity": {
            "period_consistent": period_consistent,
            "valid_ratio":       valid_ratio,
            "warnings":          warnings,
        },
    }


# ── Sanity rules ───────────────────────────────────────────────────────────────
# Per-KPI numeric bounds. Values from parse_numeric are in percentage-points for
# "%" KPIs (e.g. churn_rate=2.1 means 2.1%) and raw USD for "$" KPIs.
# None = no bound on that side.

SANITY_RULES: dict[str, dict] = {
    # Percentage KPIs ────────────────────────────────────────────────────────
    "churn_rate": {
        "label":            "Churn Rate",
        "unit":             "%",
        "min":              None,
        "max":              100.0,
        "rule_description": "Churn Rate no puede superar el 100%",
    },
    "gross_profit_margin": {
        "label":            "Gross Profit Margin",
        "unit":             "%",
        "min":              -100.0,
        "max":              100.0,
        "rule_description": "Gross Margin debe estar entre -100% y 100%",
    },
    "ebitda_margin": {
        "label":            "EBITDA Margin",
        "unit":             "%",
        "min":              -500.0,
        "max":              100.0,
        "rule_description": "EBITDA Margin no puede superar 100%",
    },
    "npl_ratio": {
        "label":            "NPL Ratio",
        "unit":             "%",
        "min":              0.0,
        "max":              100.0,
        "rule_description": "NPL Ratio debe estar entre 0% y 100%",
    },
    "loss_ratio": {
        "label":            "Loss Ratio",
        "unit":             "%",
        "min":              0.0,
        "max":              200.0,
        "rule_description": "Loss Ratio debe estar entre 0% y 200%",
    },
    "revenue_growth": {
        "label":            "Revenue Growth",
        "unit":             "%",
        "min":              -100.0,
        "max":              None,
        "rule_description": "Revenue Growth no puede ser menor a -100%",
    },
    # USD KPIs that must be non-negative by definition ───────────────────────
    "cash_in_bank_end_of_year": {
        "label":            "Cash in Bank",
        "unit":             "$",
        "min":              0.0,
        "max":              None,
        "rule_description": "El saldo de caja (Cash) no puede ser negativo",
    },
    "portfolio_size": {
        "label":            "Loan Portfolio Size",
        "unit":             "$",
        "min":              0.0,
        "max":              None,
        "rule_description": "El tamaño del portafolio no puede ser negativo",
    },
    "gmv": {
        "label":            "GMV",
        "unit":             "$",
        "min":              0.0,
        "max":              None,
        "rule_description": "GMV no puede ser negativo",
    },
    "cac": {
        "label":            "CAC",
        "unit":             "$",
        "min":              0.0,
        "max":              None,
        "rule_description": "CAC no puede ser negativo",
    },
    "mrr": {
        "label":            "MRR",
        "unit":             "$",
        "min":              0.0,
        "max":              None,
        "rule_description": "MRR no puede ser negativo",
    },
}


def validate_founder_submission(
    kpi_rows: list[dict],
    bucket_id: str,
) -> Optional[dict]:
    """
    Two-gate validator for founder submissions.

    Gate 1 — Mandatory completeness
        Checks that every KPI required for ``bucket_id`` has a valid numeric
        value extracted by Gemini.  Uses SECTOR_REQUIREMENTS as the source of
        truth.  Missing fields are returned with their human-readable label so
        the frontend can render a named rescue form.

    Gate 2 — Sanity ranges
        Checks every extracted value against SANITY_RULES bounds.
        Violations do NOT block storage (the document is already written) but
        are returned so the frontend can demand a written justification that
        will be stored as ``analyst_note`` alongside the corrected value.

    Returns
    -------
    None
        Submission passes both gates — no action required.
    dict
        ``{ "missing_mandatory_fields": [...], "sanity_violations": [...] }``
        At least one list is non-empty when the dict is returned.
    """
    # Index of valid extracted values: kpi_key → numeric_value
    valid_index: dict[str, float] = {
        r["kpi_key"]: r["numeric_value"]
        for r in kpi_rows
        if r.get("is_valid") and r.get("numeric_value") is not None
    }

    # ── Gate 1: mandatory fields ───────────────────────────────────────────
    required_keys = SECTOR_REQUIREMENTS.get(bucket_id, [])
    _label_map = {k["kpi_key"]: k["kpi_label"] for k in KPI_REGISTRY}

    missing_mandatory_fields = [
        {
            "kpi_key": key,
            "label":   _label_map.get(key, key.replace("_", " ").title()),
        }
        for key in required_keys
        if key not in valid_index
    ]

    # ── Gate 2: sanity ranges ──────────────────────────────────────────────
    sanity_violations = []
    for kpi_key, rule in SANITY_RULES.items():
        value = valid_index.get(kpi_key)
        if value is None:
            continue  # absent values are handled by Gate 1, not Gate 2

        lo: Optional[float] = rule["min"]
        hi: Optional[float] = rule["max"]
        violated = (lo is not None and value < lo) or (hi is not None and value > hi)

        if violated:
            sanity_violations.append({
                "kpi_key":               kpi_key,
                "label":                 rule["label"],
                "value":                 value,
                "rule_description":      rule["rule_description"],
                "requires_justification": True,
            })

    if not missing_mandatory_fields and not sanity_violations:
        return None

    return {
        "missing_mandatory_fields": missing_mandatory_fields,
        "sanity_violations":        sanity_violations,
    }


# ── Gemini-powered PDF extractor (UnifiedKPIContract) ─────────────────────────
# Reemplaza build_contract() como punto de entrada para el flujo PDF.
# build_contract() se mantiene para compatibilidad del flujo de analista
# (finalize-analysis) hasta su migración completa.


def _init_gemini_model_pdf() -> "Any":
    """
    Inicializa el modelo Gemini para extracción de PDFs.
    Mismo orden de credenciales que GeminiAuditor y kpi_mapper._init_gemini_model.
    """
    import json as _json
    import os

    import vertexai
    from google.oauth2 import service_account
    from vertexai.generative_models import GenerativeModel

    project_id = os.getenv("GOOGLE_PROJECT_ID", "cometa-mvp")
    location   = os.getenv("VERTEX_AI_LOCATION", "us-central1")
    model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    sa_json_str = os.getenv("GCP_SERVICE_ACCOUNT_JSON")
    sa_path     = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "cometa_key.json")

    if sa_json_str:
        info = _json.loads(sa_json_str.strip())
        if isinstance(info, str):
            info = _json.loads(info)
        creds = service_account.Credentials.from_service_account_info(info)
        vertexai.init(project=project_id, location=location, credentials=creds)
    elif os.path.isfile(sa_path):
        creds = service_account.Credentials.from_service_account_file(sa_path)
        vertexai.init(project=project_id, location=location, credentials=creds)
    else:
        vertexai.init(project=project_id, location=location)

    return GenerativeModel(model_name)


def _build_pdf_kpi_catalog() -> str:
    """Genera el catálogo compacto de KPIs GIVEN para el prompt de extracción de PDF."""
    import sys

    try:
        with open(_BRAIN_PATH, encoding="utf-8") as f:
            brain = json.load(f)
        lines: list[str] = []
        for m in brain.get("metrics", []):
            if m.get("given_or_silver") != "GIVEN":
                continue
            mid     = m.get("metric_id", "")
            dname   = m.get("display_name", mid)
            unit    = m.get("unit", "?")
            aliases = ", ".join(m.get("aliases", [])[:3])
            entry   = f'  "{mid}": {dname} [unit: {unit}]'
            if aliases:
                entry += f' — aliases: {aliases}'
            lines.append(entry)
        return "\n".join(lines)
    except Exception as exc:
        print(f"[data_contract] WARN: catálogo PDF no disponible: {exc}", file=sys.stderr)
        return ""


def extract_pdf_to_contract(
    pdf_bytes: bytes,
    period_id: str,
) -> "UnifiedKPIContract":
    """
    Extrae métricas de un PDF usando Gemini Vision y las retorna
    como UnifiedKPIContract validado.

    Gemini recibe el PDF completo como dato inline junto al catálogo
    de 109 KPIs y tiene la instrucción de devolver EXCLUSIVAMENTE el
    JSON del contrato.  Si la respuesta no es parseable como
    UnifiedKPIContract, la función levanta ValueError — cero lógica
    condicional post-IA.

    Parameters
    ----------
    pdf_bytes : Contenido binario del PDF.
    period_id : Período canónico inyectado en cada métrica (ej. "P2026Q1M01").

    Returns
    -------
    UnifiedKPIContract validado.

    Raises
    ------
    ValueError  : Si Gemini no devuelve JSON válido conforme al contrato.
    RuntimeError: Si Gemini no está disponible (sin credenciales).
    """
    # Deferred import to avoid circular dependency at module load time
    from src.schemas import UnifiedKPIContract  # noqa: PLC0415

    import json as _json  # noqa: PLC0415

    from vertexai.generative_models import GenerationConfig, Part  # noqa: PLC0415

    catalog = _build_pdf_kpi_catalog()

    from src.core.prompts import build_extraction_prompt  # noqa: PLC0415

    prompt = build_extraction_prompt(
        catalog=catalog,
        period_id=period_id,
        source="PDF",
        raw_data_label="el documento financiero adjunto",
    )

    try:
        model    = _init_gemini_model_pdf()
        config   = GenerationConfig(response_mime_type="application/json", temperature=0.0)
        pdf_part = Part.from_data(data=pdf_bytes, mime_type="application/pdf")
        response = model.generate_content([prompt, pdf_part], generation_config=config)
        parsed   = _json.loads(response.text)
        contract = UnifiedKPIContract.model_validate(parsed)
        return contract

    except Exception as exc:
        raise ValueError(
            f"Gemini no pudo producir un UnifiedKPIContract válido desde el PDF: {exc}"
        ) from exc
